# -*- coding: utf-8 -*-
"""MedieMobili.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zeireSpMJo5J-0teF9lS4y6gTOb0iFG5
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

end_date = datetime.now()
start_date = "2024-01-01"
data = yf.download('AAPL', start=start_date, period="1d")
close_prices = data['Close']

### -------------------------------------------- MOVING AVERAGE

# Calcola la media mobile a 20 periodi (media a breve)
media_breve = close_prices.rolling(window=20).mean()

# Calcola la media mobile a 50 periodi (media a lunga)
media_lunga = close_prices.rolling(window=50).mean()

# Plot dei dati
plt.figure(figsize=(10, 4))
plt.plot(close_prices, label='AAPL', color='blue')
plt.plot(media_breve, label='Media a breve (20 periodi)', color='orange')
plt.plot(media_lunga, label='Media a lunga (50 periodi)', color='green')
plt.title('Prezzi di Chiusura AAPL e Medie Mobili (Ultimo Anno)')
plt.xlabel('Data')
plt.ylabel('Prezzo ($)')
plt.legend()
plt.grid(True)
plt.show()

